ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'FUNCIONARIO';

ALTER TABLE "User" ALTER COLUMN "role" SET DEFAULT 'FUNCIONARIO';
ALTER TABLE "Funcionario" ALTER COLUMN "cargo" SET DEFAULT 'FUNCIONARIO';

ALTER TABLE "Comanda" ADD COLUMN "pagoEm" TIMESTAMP(3);

ALTER TABLE "Configuracao" ADD COLUMN "pixChave" TEXT NOT NULL DEFAULT '';
